name: Integration test reusable workflow
on:
  workflow_call:
permissions:
  id-token: write
jobs:
  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: oidc
        id: oidc
        uses: ./
      - name: checkout-actions-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          repository: ${{ steps.oidc.outputs.job_workflow_repo_name_and_owner }}
          path: ./test-repo
          ref: ${{ steps.oidc.outputs.job_workflow_repo_ref }}
      - name: Validate oidc
        env:
          REPO: ${{ steps.oidc.outputs.job_workflow_repo_name_and_owner }}
          WORKFLOW_REF: ${{ steps.oidc.outputs.job_workflow_repo_ref }}
        run: |
          echo "REPO: $REPO"
          echo "WORKFLOW_REF: $WORKFLOW_REF"